### ISSUE TITLE
Notifications (while qi charging)

### ISSUE THREAD

**Issue by Ceuse** [yoavst/quickapps#20]
I got woke up tonight by constantly active notification widget. I think its because of the qi charging that the screen wont turn black. Please add a timeout for turning black again.

**Comment by nabulaer** [comment]
are you using Lollipop ? cause my friend has upgraded to lollipop on his G3 and same thing happen to him. he does not have the quickapps installed. if you did , suspect this is a G3 firmware issue.

**Comment by Ceuse** [comment]
True lollypop. But only notifications were the problem. As soon as i removed them screen turned black again. Gotta check this again if im charging again tonight

**Comment by nabulaer** [comment]
I use the LG Original Wireless Charger , my friend tried to put his device on my charger and  it kept opening the display saying charging has started over and over again. also notice the difference in the screen , lollipop display the charging message with a back button on the bottom while kitkat is a full black screen with the battery charging image. my friend does not have quickcircle cover so i do not know how it look with lollipop  and the cover.

**Comment by Ceuse** [comment]
It was all black till i got a email at 2am+ then the quick notifaction was shown till i woke up by the light and removed it. It then went back to black. I know the error you described aswell but it got fixed / a reboot solved my problem

**Comment by Ceuse** [comment]
Also the charging bug was diffrent. It lighted up showing charging. Then went back to blwck. Then a minute later it lighted up again. Not constantly like i expirienced tonight

**Comment by yoavst** [comment]
Can you update me if it is my bug or LG's bug? you can disable launch of quick notifications on notification arrived on app settings.

**Comment by yoavst** [comment]
@Ceuse ?
