### ISSUE TITLE
Calculator crashes when answer is dividend of 10

### ISSUE THREAD

**Issue by inebritov** [yoavst/quickapps#28]
My device is LG G3 D855 16Gb. Some test cases:
12*65=
770+10=
779+1=

**Comment by inebritov** [comment]
Sorry, it not depends on 780 answer, issue reproduces with any dividend of 10. Some more cases:
1+10=
10*2=
7-17=
But 1-1=0 works.

**Comment by yoavst** [comment]
I think I've lost the keystore after I upgraded to win 10 :(
So it is impossible for now to update in Play Store anyway :(

**Comment by inebritov** [comment]
It's not good :( calculations in Quick Circle mode is very comfortable. Do you know alternative calc apps?
